import Navbar from '@/components/Navbar';
import './globals.css'

export const metadata = {
  title: 'Next users display',
  description: 'Generated by create next app',
  keywords: 'react,next,users,fetch',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='stylesheet' href='https://bootswatch.com/5/pulse/bootstrap.min.css'/>
      </head>
      <body>
        <Navbar />
        <div className='container p-4'>
          {children}
        </div>
      </body>
    </html>
  )
}
